task_management/activity/urls.py
from django.urls import path
from . import views

app_name = 'activity'
urlpatterns = [
    path('project/<int:project_id>', views.ProjectUpdateView.as_view(), name='project_update'),
path('project/add', views.ProjectUpdateView.as_view(), name='project_add'),
    path('project/', views.CategoryProjectView.as_view(), name='all_project'),

]

task_management/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('activity/', include('activity.urls', namespace='activitys')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_management/activity/models.py
from django.db import models
from home.models import Staff, Category


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=50, unique=True)
    constracting_party = models.CharField(max_length=50, null=True, default=None)
    work_in_progress = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    started = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(null=True, blank=True, default="1300-01-01")
    delay = models.DateField(null=True,blank=True)
    cost = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    category = models.ManyToManyField(Category, related_name='Project', default=None)
    staff = models.ManyToManyField(Staff, related_name='Project', default=None)

    def __str__(self):
        return f"{self.title} started at {self.started}_{self.work_in_progress}"

task_management/activity/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

task_management/activity/views.py
from django.shortcuts import render
from django.views import View
from .models import Project
from .forms import ProjectForm
from home.models import Category, Staff
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect


# Create your views here.
class CategoryProjectView(View):
    template_name = 'activity/all_project.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user_id = request.user.id
            return self.get(request, user_id)
        return super().dispatch(request, user_id=None, *args, **kwargs)

    def get(self, request, user_id):
        all_project = Project.objects.all()
        categories = Category.objects.all()
        context = {
            'all_project': all_project,
            'categories': categories,
        }
        if user_id:
            log_staff = get_object_or_404(Staff, user_id=user_id)
            context['log_staff_category'] = log_staff.categories
        return render(request, self.template_name, context)

    class ProjectUpdateView(View):
        template_name = "activity/project-update.html"
        project_form = ProjectForm

        def get(self, request, project_id):
            project = Project.objects.get(project_id=project_id)
            form = self.project_form(instance=project)
            return render(request, self.template_name, {'form': form})

        def post(self, request, project_id):
            project = Project.objects.get(project_id=project_id)
            form = self.project_form(request.POST, instance=project)
            if form.is_valid():
                form.save()
                messages.success(request, f"update successfully", "success")
                # return redirect("home:home")
                return HttpResponseRedirect(reverse('activity:all_project'))
            else:
                messages.warning(request, "check your input data", "warning")
            return render(request, self.template_name, {'form': form})


class ProjectUpdateView(View):
    template_name = "activity/project_update.html"
    project_form = ProjectForm

    def get(self, request, project_id=None):
        if project_id:
            project = Project.objects.get(id=project_id)
            form = self.project_form(instance=project)
        else:
            form = self.project_form()
        return render(request, self.template_name, {'form': form})

    def post(self, request, project_id=None):
        if project_id:
            project = Project.objects.get(id=project_id)
            form = self.project_form(request.POST, instance=project)
        else:
            form = self.project_form(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f"update successfully", "success")
            # return redirect("home:home")
            return HttpResponseRedirect(reverse('activity:all_project'))
        else:
            messages.warning(request, "check your input data", "warning")
        return render(request, self.template_name, {'form': form})

task_management/activity/templates/activity/all_project.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ category_name }} {% endblock %}
{% block content %}
   {% for category in categories %}
      <h1 class="card bg-primary col-md-12 mb-12 m-3 p-3 text-center mx-auto">{{ category.title }}</h1>
      <span class="border-0">
      <div class="row">
         {% for project in all_project %}
            <div class="col-md-3 mb-4">
            <div class="card border-primary mb-3 pd-5 m-2">
               <p class="card-text m-3">Title: {{ project.title }}</p>
               <p class="card-text m-3">Constructing party: {{ project.constracting_party }} years</p>
               <p class="card-text m-3">work_in_progress: {{ project.constracting_party }} years</p>
                  {% if log_staff_category == category %}
                      <p class="card-text m-3">Delay: {{ project.delay }} years</p>
                      <p class="card-text m-3">Cost: {{ project.cost }} years</p>
                      <p class="card-text m-3">started: {{ project.started }} years</p>
                      <p class="card-text m-3">deadline: {{ project.deadline }} years</p>
                      <a href="{% url 'activity:project_update' project.id %}">Edite projects</a>
                  {% endif %}
            </div>
            </div>
         {% endfor %}
      </div>
       {% if log_staff_category == category %}
       <div class="card col-md-12 mb-12 m-3 p-3 text-center mx-auto" style="color: black;font-size: larger;">
         <a href="{% url 'activity:project_add'%}">Add new projects </a>
       </div>

       {% endif %}
{% endfor %}
{% endblock %}

task_management/activity/templates/activity/project_update.html
{% extends 'base.html' %}
{% block title %} Project{% endblock %}
{% block content %}
 <div class="row justify-content-center m-2 p-2">
    <div class="card border-primary col-md-8">
        <h3 class="card border-primary text-center m-3 text-white" style="background-color: #032a5d;">Please fill in the blank of project form </h3>
        <form method="post" novalidate autocomplete="off">
            {% csrf_token %}
            <div class="form-group">
                {{ form.title.label_tag }}
                {{ form.title }}
            </div>
            <div class="form-group">
                {{ form.constracting_party.label_tag }}
                {{ form.constracting_party}}
            </div>
            <div class="form-group">
                {{ form.work_in_progress.label_tag }}
                {{ form.work_in_progress}}
            </div>
            <div class="form-group">
                {{ form.started.label_tag }}
                {{ form.started}}
            </div>
            <div class="form-group">
                {{ form.deadline.label_tag }}
                {{ form.deadline}}
            </div>
            <div class="form-group">
                {{ form.delay.label_tag }}
                {{ form.delay}}
            </div>
            <div class="form-group">
                {{ form.cost.label_tag }}
                {{ form.cost}}
            </div>
            <div class="form-group">
                {{ form.category.label_tag }}
                {{ form.category}}
            </div>
            <div class="form-group">
                {{ form.staff.label_tag }}
                {{ form.staff}}
            </div>
            <button type="submit" class="btn btn-dark text-white" style="max-width: 100px;">update</button> 
        </form>
    </div>
 </div>
{% endblock %}