task_management/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='User_register'),
    path('login/', views.UserLoginView.as_view(), name='User_login'),
    path('logout/', views.UserLogoutView.as_view(), name='User_logout'),
]

task_management/home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about_us/', views.AboutUsView.as_view(), name='about_us'),
    path('contact_us/', views.ContactUsView.as_view(), name='contact_us'),
    path('profile/<int:user_id>', views.ProfileUpdateView.as_view(), name='ProfileUpdate'),
    path('profile/<str:title>', views.CategoryDetailView.as_view(), name='categorydetail'),
    path('profile', views.StaffPdetailView.as_view(), name='staffpdetail'),
    path('delete/<int:user_id>', views.StaffDeleteView.as_view(), name='staffdelete'),
]

task_management/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('activity/', include('activity.urls', namespace='activitys')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_management/home/models.py
from django.db import models
from account.models import CustomUser
import os, uuid


# def user_image_file_path(instance, filename: str):
#     """generate file path for user profile image"""
#     ext = filename.split('.')[-1]
#     filename = f'{uuid.uuid4()}.{ext}'
#     return os.path.join('uploads/user/', filename)


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=50)
    employe_rewards = models.CharField(max_length=250,
                                       choices=[("To", "Time off"), ("G", "Gifts"), ("WH", "Work from home days"),
                                                ("Gc", "Gift cards"), ("C", "Certificates")], default="None")

    def __str__(self):
        return f"{self.title}"


class Staff(models.Model):
    firstname = models.CharField(max_length=50, null=True, default=None)
    lastname = models.CharField(max_length=50, null=True, default=None)
    expert = models.CharField(max_length=50, null=True, default=None)
    experience = models.IntegerField(null=True, default=None)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='staff', null=True, default=None)
    profile_image = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return f"{self.firstname} {self.lastname} in {self.categories.title}"

task_management/home/forms.py
from django import forms
from .models import Staff

class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['firstname', 'lastname', 'expert', 'experience', 'user', 'categories','profile_image']

task_management/home/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Category, Staff
from account.models import CustomUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import StaffForm
from account.models import CustomUser
from django.urls import reverse
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect


# Create your views here.
class HomeView(View):
    def get(self, request):
        # allcategory=Category.objects.values_list('title', flat=True).distinct()
        allcategory = Category.objects.all()
        return render(request, 'home/home.html', {"allcategory": allcategory})

    def post(self, request):
        return render(request, 'home/home.html')


class StaffPdetailView(View):
    staff_form = StaffForm
    template_name = "home/staffpdetail.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user_id = request.user.id
            return self.get(request, user_id)
        return super().dispatch(request, user_id=None, *args, **kwargs)

    def get(self, request, user_id):
        if user_id:
            user = CustomUser.objects.get(id=user_id)
            staff = Staff.objects.get(user_id=user_id)
            context = {
                'user': user,
                'staff': staff,
            }
            return render(request, self.template_name, context)
        else:
            return redirect('home:home')
        messages.warning(request, "your not access to staff of Ada company profile", "warning")

    # def get(self, request, user_id):
    #     if request.user.is_authenticated:
    #         if request.user.has_category_permission(user_id):
    #             user= CustomUser.objects.get(id=user_id)
    #             staff = Staff.objects.get(user_id=user_id)
    #             context = {
    #              'user': user,
    #              'staff': staff,
    #             }
    #             return render(request,"home/staffdetail.html",context)
    #         staff=Staff.objects.get(user_id=user_id)
    #         form=StaffForm(instance=staff)
    #         return render(request,self.template_name,{'form':form})


class CategoryDetailView(View):

    def get(self, request, title):
        category = Category.objects.get(title=title)
        staffs = Staff.objects.filter(categories=category)
        context = {
            'category_name': category.title,
            'staffs': staffs,
            'user': request.user
        }
        return render(request, 'home/categorydetail.html', context)


class ProfileUpdateView(View):
    staff_form = StaffForm
    template_name = "home/profileupdate.html"

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'GET' and request.user.is_authenticated:
            user_id = request.user.id
            return self.get(request, user_id)
        if request.method == 'POST' and request.user.is_authenticated:
            user_id = request.user.id
            return self.post(request, user_id)
            # return super().dispatch(request,user_id, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, user_id):
        staff = Staff.objects.get(user_id=user_id)
        form = StaffForm(instance=staff)
        return render(request, self.template_name, {'form': form})

    def post(self, request, user_id):
        staff = Staff.objects.get(user_id=user_id)
        form = self.staff_form(request.POST, request.FILES, instance=staff)
        if form.is_valid():
            a = form.save()
            messages.success(request, f"update successfully", "success")

            # return redirect("home:home")
            return HttpResponseRedirect(reverse('home:staffpdetail'))
        else:

            messages.warning(request, "check your input data", "warning")
        return render(request, self.template_name, {'form': form})


class StaffDeleteView(View):

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user_id = request.user.id
            return self.get(request, user_id)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, user_id):
        staff = Staff.objects.get(user_id=user_id)
        user = CustomUser.objects.get(user_id=user_id)

        title = staff.categories.title
        staff.delete()
        user.delete()
        url = reverse("home:categorydetail", args=[title])
        return redirect(url)


class AboutUsView(TemplateView):
    template_name = 'about_us.html'


class ContactUsView(TemplateView):
    template_name = 'contact_us.html'

task_management/home/templates/home/categorydetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ category_name }} {% endblock %}
{% block content %}
  <h1 class="card bg-primary m-3 p-3 text-center mx-auto">{{ category_name }}</h1>
  <span class="border-0">
  <div class="row">
    {% for staff_member in staffs %}
      <div class="col-md-3 mb-4">
        <div class="card border-primary mb-3 pd-5 m-2">
          <img src="{% static 'image/staff.jpg' %}" class="card-img-top" alt="...">
          <h5 class="card-header border-primary pd-5">{{ staff_member.firstname }} {{ staff_member.lastname }}</h5>
          <p class="card-text m-3">Expertise: {{ staff_member.expert }}</p>
          <p class="card-text m-3">Experience: {{ staff_member.experience }} years</p>
          {% if user.is_authenticated and user.id == staff_member.user.id %}
          <button type="button" class="btn btn-light"><a href="{% url 'home:staffpdetail' %}">detail</a></button>
          {% endif %}
          {% if user.is_admin or user.is_authenticated and user.id == staff_member.user.id %}
          <button type="button" class="btn btn-light"><a href="{% url 'home:staffdelete' staff_member.user_id %}">delete</a></button>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

task_management/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} home {% endblock %}
{% block content %}
  <div class="row">  
{% for category in allcategory %}
    <div class="col-md-6 mb-6">
      <div class="card">
        <a class="card-img-top p-2" href="{% url 'home:categorydetail' category.title %}">
        <img src={% static 'image/'|add:category.title|add:'.jpg' %} class="card-img-top p-2" alt="category Image"> 
        </a>
        <div class="card-body  text-center">
          <h5 class="card-title">{{category.title}}</h5>
        </div>
      </div>
    </div>
{% endfor %}
</div>
{% endblock %}

task_management/home/templates/home/profile.html
{% extends 'base.html' %}
{% block title %} login{% endblock %}
{% block content %}
 <div class="row-form m-2 p-2">
     <div class="col-md-6">
         <h2 class="m-3 text-white">login form</h2>
         <form action="" method="post" novalidate autocomplete="off">
             {% csrf_token %}
             <div class="form-group">
                 {{ form.firstname.label_tag }}
                 {{ form.firstname }}
             </div>
             <div class="form-group">
                 {{ form.lastname.label_tag }}
                 {{ form.lastname}}
             </div>
             <div class="form-group">
                 {{ form.expert.label_tag }}
                 {{ form.expert}}
             </div>
             <div class="form-group">
                 {{ form.experience.label_tag }}
                 {{ form.experience}}
             </div>
             <div class="form-group">
                 {{ form.user.label_tag }}
                 {{ form.user}}
             </div>
             <div class="form-group">
                 {{ form.categories.label_tag }}
                 {{ form.categories}}
             </div>
             <a href="{% url 'account:User_login' %}" class="sing_up_sign_in" target="_self">
             <button type="submit" class="btn btn-primary btn-sm btn-block" style="max-width: 100px;">update</button>
             </a>
         </form>
     </div>
 </div>
{% endblock %}

task_management/home/templates/home/profileupdate.html
{% extends 'base.html' %}
{% block title %}profile{% endblock %}
{% block content %}
 <div class="row justify-content-center m-2 p-2">
    <div class="card border-primary text-center col-md-8">
        <h3 class="card border-primary m-3 text-white" style="background-color: #032a5d;">Please fill in the blank of profile form </h3>
        <form method="post" enctype="multipart/form-data" novalidate autocomplete="off">
            {% csrf_token %}
            <div class="form-group">
                {{ form.firstname.label_tag }}
                {{ form.firstname }}
            </div>
            <div class="form-group">
                {{ form.lastname.label_tag }}
                {{ form.lastname}}
            </div>
            <div class="form-group">
                {{ form.expert.label_tag }}
                {{ form.expert}}
            </div>
            <div class="form-group">
                {{ form.experience.label_tag }}
                {{ form.experience}}
            </div>
            <div class="form-group">
                {{ form.user.label_tag }}
                {{ form.user}}
            </div>
            <div class="form-group">
                {{ form.categories.label_tag }}
                {{ form.categories}}
            </div>
            <div>
                <label for="{{ form.profile_image.id_for_label }}">Image:</label>
                {{ form.profile_image }}
                {{ form.profile_image.errors}}
            </div>
            <button type="submit" class="btn btn-dark text-white" style="max-width: 100px;">update</button> 
        </form>
    </div>
 </div>
{% endblock %}

task_management/home/templates/home/staffpdetail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{staff.lastname}} profile{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <img src="{% static 'image/staff.jpg' %}" class="card-img-top" alt="...">
    </div>
    <div class="row">
      <div class="card border-primary text-center col-md-12 m-2">
        <div class="card-header border-primary pd-5 m-2"><h2 class="card-title">Personal Data</h2></div>
        <p><strong>First Name:</strong> {{ staff.firstname }}</p>
        <p><strong>Last Name:</strong> {{ staff.lastname }}</p>
        <p><strong>National Code:</strong> {{ staff.user.nationalcode }}</p>
        <p><strong>Email:</strong> {{ staff.user.email }}</p>
        <p><strong>Address:</strong> {{ staff.user.adress }}</p>
        <p><strong>Date of Birth:</strong> {{ staff.user.date_of_birth }}</p>
      </div>
      <div class="card border-primary text-center  col-md-12 m-2">
        <div class="card-header border-primary m-2"><h2 class="card-title">About Expertise</h2></div>
        <p><strong>Expertise:</strong> {{ staff.expert }}</p>
        <p><strong>Experience:</strong> {{ staff.experience }} years</p>
        <p><strong>Category:</strong> {{ staff.categories.title }}</p>
        <a href="{% url 'home:ProfileUpdate' staff.user_id %}" style="color:blue ;font-size: 18px;">detail</a>
      </div>
    </div>
  </div>
{% endblock %}

task_management/home/templates/home/staffprofile.html
{% extends 'base.html' %}
{% block title %} login{% endblock %}
{% block content %}
 <div class="row-form m-2 p-2">
     <div class="col-md-6">
         <h2 class="m-3 text-white">Please fill in the blank of profile form </h2>
         <form action="" method="post" novalidate autocomplete="off">
             {% csrf_token %}
             <div class="form-group">
                 {{ form.firstname.label_tag }}
                 {{ form.firstname }}
             </div>
             <div class="form-group">
                 {{ form.lastname.label_tag }}
                 {{ form.lastname}}
             </div>
             <div class="form-group">
                 {{ form.expert.label_tag }}
                 {{ form.expert}}
             </div>
             <div class="form-group">
                 {{ form.experience.label_tag }}
                 {{ form.experience}}
             </div>
             <div class="form-group">
                 {{ form.user.label_tag }}
                 {{ form.user}}
             </div>
             <div class="form-group">
                 {{ form.categories.label_tag }}
                 {{ form.categories}}
             </div>
             <a href="{% url 'account:User_login' %}" class="sing_up_sign_in" target="_self">
             <button type="submit" class="btn btn-primary btn-sm btn-block" style="max-width: 100px;">update</button>
             </a>
         </form>
     </div>
 </div>
{% endblock %}