task_management/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='User_register'),
    path('login/', views.UserLoginView.as_view(), name='User_login'),
    path('logout/', views.UserLogoutView.as_view(), name='User_logout'),
]

task_management/activity/urls.py
from django.urls import path
from . import views

app_name = 'activity'
urlpatterns = [
    path('project/<int:project_id>', views.ProjectUpdateView.as_view(), name='project_update'),
path('project/add', views.ProjectUpdateView.as_view(), name='project_add'),
    path('project/', views.CategoryProjectView.as_view(), name='all_project'),

]

task_management/home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about_us/', views.AboutUsView.as_view(), name='about_us'),
    path('contact_us/', views.ContactUsView.as_view(), name='contact_us'),
    path('profile/<int:user_id>', views.ProfileUpdateView.as_view(), name='ProfileUpdate'),
    path('profile/<str:title>', views.CategoryDetailView.as_view(), name='categorydetail'),
    path('profile', views.StaffPdetailView.as_view(), name='staffpdetail'),
    path('delete/<int:user_id>', views.StaffDeleteView.as_view(), name='staffdelete'),
]

task_management/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('activity/', include('activity.urls', namespace='activitys')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_management/templates/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block title %} about us {% endblock %}
{% block content %}
    <section class="container about-section">
      <div class="row">
          <div class="card border-primary m-2 ml-5 col-sm-12 col-md-6 col-lg-4"style="margin-right: 3rem;">
              <h2>About Us</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                  aliquip ex ea commodo consequat.</p>
              <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                  est laborum.</p>
          </div>
          <div class="col-sm-12 col-md-6 col-lg-6 about-image m-2" style="margin-left: 3rem;">
              <img  class="img-fluid rounded" src={% static 'image/contact-us.jpg' %} alt="Responsive image">
          </div>
      </div>

    </section>
{% endblock %}

task_management/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href={% static 'image/company_logo.png' %}>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<header>
    <div class="container-fluid">
        <div class="nav_belt">
            <div class="row align-items-center">
                <div class="company-logo col-lg-2 col-md-2 col-sm-3 col-6 ">
                   <img src={% static 'image/company_logo.png' %}  alt = "logo Image">
                    <a style="color:whitesmoke; font-family: cursive; text-decoration:none;" href="{% url 'home:home' %}" ><b>Ada company</b></a>
                </div> 
                <div class="col-lg-1 col-md-2 col-sm-3 col-12 menu-icon">
                    <div class="dropdown">
                        <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  MENU</button>
                        <div class="dropdown-menu " aria-labelledby="dropdownMenu2">
                            <button class="dropdown-item" type="button"><a href="{% url 'activitys:all_project' %}" target="_self">Ada Projects</a></button>
                            <button class="dropdown-item" type="button"><a href="{%url 'home:about_us' %}">about us</a></button>
                            <button class="dropdown-item" type="button"><a href="{%url 'home:contact_us' %}">contact us</a></button>
                            <button class="dropdown-item" type="button"><a style="color:black; text-decoration:none" href="{% url 'account:User_logout' %}" >User Logout</a></button>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                    <input type="text" class="form-control search-box" placeholder=" Search Ada company ...">
                </div>
                {% if user.is_authenticated %}
                    <div class="col-lg-2 col-md-2 col-sm-3 col-12">
                       <button type="button" class="btn btn-dark"><a style="color:white; text-decoration:none" href="{% url 'home:staffpdetail'%}" type="submit" target="_self">profile</a></button>
                    </div>
                {% else %}
                    <div class="col-lg-2 col-md-2 col-sm-3 col-6">
                       <button type="button" class="btn btn-dark"><a style="color:white; text-decoration:none" href="{% url 'account:User_register' %}" type="submit" target="_self">register</a></button>
                       <button type="button" class="btn btn-dark"><a style="color:white; text-decoration:none" href="{% url 'account:User_login' %}" type="submit" target="_self">log in</a></button>
                    </div>
                {% endif %}
            </div>
        </div>
</header>
<body>
    <div class="container mt-2">
      {% include "include/messages.html" %}
      {% block content %}
      {% endblock %}
    </div>
    
    <div class="footer col-md-12 mb-12 m-0">
      {% comment %} <img src={% static 'image/footer.png' %} alt="Your Image Alt Text" class="footer-image"> {% endcomment %}
            <div class="social-icons">
              <a href="https://www.instagram.com/digikalacom/?utm_source=aboutdk_home&utm_medium=web&utm_campaign=refactor" target="_blank"><i class="fab fa-instagram"></i></a>
              <a href="https://www.linkedin.com/company/digikala/?originalSubdomain=ir" target="_blank"><i class="fab fa-linkedin"></i></a>
            </div>
            <p>&copy; 2023 To use the contents of the website about the Ada group, it is enough to have a "non-commercial purpose" and mention the "source".</p>
            <p>&copy; All the rights of this website belong to Ada e-commerce group company.</p>
  
    </div>
    
    
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</body>
</html>

task_management/templates/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% block title %} contact us {% endblock %}
{% block content %}
  <section class="container mt-5">
    <div class="row">
      <div class="card border-primary ml-2 col-lg-5">
        <h2>Contact Us</h2>
        <p >Feel free to reach out to us with any questions or concerns. We are here to help!</p>
        <form>
          <div class="form-group">
            <label for="name">Your Name</label>
            <input type="text" class="form-control" id="name" placeholder="Enter your name">
          </div>
          <div class="form-group">
            <label for="email" >Your Email</label>
            <input type="email" class="form-control" id="email" placeholder="Enter your email">
          </div>
          <div class="form-group">
            <label for="message">Your Message</label>
            <textarea class="form-control" id="message" rows="4" placeholder="Enter your message"></textarea>
          </div>
          <a type="submit" class="btn btn-dark btn-sm mg-2" >Submit</a>
        </form>
      </div>
      <div class="col-lg-4 mg-2" style="margin-top: 6rem;margin-left: 4rem;">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d404.78127997199306!2d51.393494505789825!3d35.744653680727524!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sde!4v1699781239809!5m2!1sen!2sde" 
        width="400" height="300" style="border: 15px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
        </iframe>
      </div>
    </div>
  </section>
{% endblock %}